### PR TITLE
[18.0][mail_cleanup]FIX : respect method signature

### PR DESCRIPTION
**Pull request by leemannd**
` TypeError: FetchmailServer.fetch_mail() got an unexpected keyword argument 'raise_exception' `

image-20250711-084847

### CODE REVIEW

**Review by wouitmil — APPROVED** [review]

**Review by santostelmo — APPROVED** [review]

**Review by Ricardoalso — CHANGES_REQUESTED** [review]
raise_exception should be passed to the super call https://github.com/OCA/server-tools/pull/3333/files#diff-77eade508f4aff5df5a30f49984ca899c9bc5b476d21d099e90945818d57f3ebL143

**Comment by leemannd** [comment]
@Ricardoalso Thanks fixed

**Review by Ricardoalso — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]
Thanks! The test issue causing the merge to fail is fixed in https://github.com/OCA/server-tools/pull/3343

**Comment by leemannd** [comment]
Hello  @StefanRijnhart , your other PR fixing the merge is merged. Do you have any time to merge this one?
